# gradient boosting default parameters yaml
n_estimators:
  desc: number of models in the ensemble
  value: 100

max_depth:
  desc: maximum depth of decision trees
  value: 4

learning_rate:
  desc: learning rate
  value: 0.1

random_state:
  desc: random seed for reproducibility purposes
  value: 8122022
